src/web/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('faq', views.Faq.as_view(), name='faq')
]

src/web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')), # Home route
    path('accounts/', include('allauth.urls')), # Discord routes
    path('admin/', admin.site.urls)
]

src/web/home/models.py
from django.db import models

# Create your models here.

src/web/home/views.py
from django.views.generic import TemplateView

class Home(TemplateView):
    template_name = 'home/index.html'


class Dashboard(TemplateView):
    template_name = 'home/dashboard.html'


class Faq(TemplateView):
    template_name = 'home/faq.html'

src/web/home/templates/home/base.html
{% load static %} {% load socialaccount %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Boostrap -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
        />

        <!-- Custom Styles -->
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'home/styles.css' %}"
        />
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="/">Ghost</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            target="_blank"
                            href="https://discord.gg/9pNXGa5"
                            >Discord</a
                        >
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:faq' %}">FAQ</a>
                    </li>
                </ul>
                <form class="form-inline ml-auto">
                    {% if user.is_authenticated %}
                    <div class="text-white">
                        Hello, <strong>{{ user.username }}</strong>!
                    </div>
                    <a
                        class="btn btn-primary ml-4 mr-2"
                        href="{% url 'home:dashboard' %}"
                    >
                        Dashboard
                    </a>
                    <a
                        class="btn btn-danger"
                        href="{% url 'account_logout' %}"
                    >
                        Logout
                    </a
                    >
                    {% else %}
                    <a
                        class="btn btn-outline-primary my-2 my-sm-0"
                        href="{% provider_login_url 'discord' %}"
                    >
                        Login
                    </a>
                    {% endif %}
                </form>
            </div>
        </nav>
        <div class="container">
            {% block content %} {% endblock %}
        </div>

        <!-- Footer -->
        <footer class="pt-4">
            <div class="footer-copyright text-center py-3">
                Made with <3 by
                <a href="https://example.com"> Ben</a>
            </div>
        </footer>

        <!-- Bootstrap -->
        <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

src/web/home/templates/home/dashboard.html
{% extends 'home/base.html' %}
{% block title %}Ghost - Dashboard{% endblock title %}
{% block content %}
<div class="container text-center pt-5">
        <h1>Dashboard</h1>
</div>
{% endblock content %}

src/web/home/templates/home/faq.html
{% extends 'home/base.html' %} {% block title %}Ghost - FAQ{% endblock title %}
{% block content %}
<div class="container text-center pt-5">
    <h1 class="pb-4">FAQ</h1>
    <div id="accordion">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button
                        class="btn btn-link"
                        data-toggle="collapse"
                        data-target="#collapseOne"
                        aria-expanded="true"
                        aria-controls="collapseOne"
                    >
                        Will I get banned?
                    </button>
                </h5>
            </div>

            <div
                id="collapseOne"
                class="collapse show"
                aria-labelledby="headingOne"
                data-parent="#accordion"
            >
                <div class="card-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life
                    accusamus terry richardson ad squid. 3 wolf moon officia
                    aute, non cupidatat skateboard dolor brunch. Food truck
                    quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,
                    sunt aliqua put a bird on it squid single-origin coffee
                    nulla assumenda shoreditch et. Nihil anim keffiyeh
                    helvetica, craft beer labore wes anderson cred nesciunt
                    sapiente ea proident. Ad vegan excepteur butcher vice lomo.
                    Leggings occaecat craft beer farm-to-table, raw denim
                    aesthetic synth nesciunt you probably haven't heard of them
                    accusamus labore sustainable VHS.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                    <button
                        class="btn btn-link collapsed"
                        data-toggle="collapse"
                        data-target="#collapseTwo"
                        aria-expanded="false"
                        aria-controls="collapseTwo"
                    >
                        Is this against Discord Terms of Service?
                    </button>
                </h5>
            </div>
            <div
                id="collapseTwo"
                class="collapse"
                aria-labelledby="headingTwo"
                data-parent="#accordion"
            >
                <div class="card-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life
                    accusamus terry richardson ad squid. 3 wolf moon officia
                    aute, non cupidatat skateboard dolor brunch. Food truck
                    quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,
                    sunt aliqua put a bird on it squid single-origin coffee
                    nulla assumenda shoreditch et. Nihil anim keffiyeh
                    helvetica, craft beer labore wes anderson cred nesciunt
                    sapiente ea proident. Ad vegan excepteur butcher vice lomo.
                    Leggings occaecat craft beer farm-to-table, raw denim
                    aesthetic synth nesciunt you probably haven't heard of them
                    accusamus labore sustainable VHS.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                    <button
                        class="btn btn-link collapsed"
                        data-toggle="collapse"
                        data-target="#collapseThree"
                        aria-expanded="false"
                        aria-controls="collapseThree"
                    >
                        Why do I have to pay to use the bot?
                    </button>
                </h5>
            </div>
            <div
                id="collapseThree"
                class="collapse"
                aria-labelledby="headingThree"
                data-parent="#accordion"
            >
                <div class="card-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life
                    accusamus terry richardson ad squid. 3 wolf moon officia
                    aute, non cupidatat skateboard dolor brunch. Food truck
                    quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,
                    sunt aliqua put a bird on it squid single-origin coffee
                    nulla assumenda shoreditch et. Nihil anim keffiyeh
                    helvetica, craft beer labore wes anderson cred nesciunt
                    sapiente ea proident. Ad vegan excepteur butcher vice lomo.
                    Leggings occaecat craft beer farm-to-table, raw denim
                    aesthetic synth nesciunt you probably haven't heard of them
                    accusamus labore sustainable VHS.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingFour">
                <h5 class="mb-0">
                    <button
                        class="btn btn-link collapsed"
                        data-toggle="collapse"
                        data-target="#collapseFour"
                        aria-expanded="false"
                        aria-controls="collapseFour"
                    >
                        Is my token secure?
                    </button>
                </h5>
            </div>
            <div
                id="collapseFour"
                class="collapse"
                aria-labelledby="headingThree"
                data-parent="#accordion"
            >
                <div class="card-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life
                    accusamus terry richardson ad squid. 3 wolf moon officia
                    aute, non cupidatat skateboard dolor brunch. Food truck
                    quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,
                    sunt aliqua put a bird on it squid single-origin coffee
                    nulla assumenda shoreditch et. Nihil anim keffiyeh
                    helvetica, craft beer labore wes anderson cred nesciunt
                    sapiente ea proident. Ad vegan excepteur butcher vice lomo.
                    Leggings occaecat craft beer farm-to-table, raw denim
                    aesthetic synth nesciunt you probably haven't heard of them
                    accusamus labore sustainable VHS.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/web/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load socialaccount %}

<!-- Title -->
{% block title %}Ghost{% endblock title %}
<!-- Content -->
{% block content %}
<div class="text-center pt-5">
    <div class="jumbotron">
        <h1 class="display-4">Ghost</h1>
        <p class="lead">
            Advanced Discord self-bot that allows you to reach maximum meme
            potential!
        </p>
        <a
            class="btn btn-primary btn-lg mr-5 pr-4 pl-4"
            href="{% provider_login_url 'discord' %}"
            role="button"
            >Login</a
        >
        <a class="btn btn-light btn-lg pr-4 pl-4" href="#" role="button"
            >Features</a
        >
    </div>
    <div class="row pb-5 pt-5">
        <div class="col my-auto">
            <h4>Title 1 Title 2</h4>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in
            aliquet quam, non vestibulum felis. Cras eu pharetra lacus.
            Curabitur porttitor nunc id nulla blandit fermentum.
        </div>
        <div class="col my-auto">
            <img src="http://via.placeholder.com/300" class="img-fluid" />
        </div>
    </div>
    <div class="row pt-5">
        <div class="col my-auto">
            <img src="http://via.placeholder.com/300" class="img-fluid" />
        </div>
        <div class="col my-auto">
            <h4>This is a cool feature title</h4>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in
            aliquet quam, no
        </div>
    </div>
    <div class="row pb-5 pt-5">
        <div class="col my-auto">
            <h4>Title 1 Title 2</h4>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in
            aliquet quam, non vestibulum felis. Cras eu pharetra lacus.
            Curabitur porttitor nunc id nulla blandit fermentum.
        </div>
        <div class="col my-auto">
            <img src="http://via.placeholder.com/300" class="img-fluid" />
        </div>
    </div>
    <div class="row pt-5">
        <div class="col my-auto">
            <img src="http://via.placeholder.com/300" class="img-fluid" />
        </div>
        <div class="col my-auto">
            <h4>This is a cool feature title</h4>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in
            aliquet quam, no
        </div>
    </div>
</div>
{% endblock content %}